# Generated by Django 4.2.4 on 2023-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('articles', '0001_initial'),
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_article',
            field=models.ManyToManyField(related_name='article_liked_user', to='articles.article'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_playlist',
            field=models.ManyToManyField(related_name='playlist_liked_user', to='movies.playlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_review',
            field=models.ManyToManyField(related_name='review_liked_user', to='movies.review'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_movie',
            field=models.ManyToManyField(related_name='movie_watched_user', to='movies.movie'),
        ),
    ]
